#!/bin/bash
#SBATCH -N 1 --ntasks-per-node=128
#SBATCH -t 18:00:00
#SBATCH -p RM
#SBATCH -J 'ion_partition2'
#SBATCH -o '%x.out'
#SBATCH --mail-type=ALL
#SBATCH --mail-user=nasc4134@colorado.edu

module load gcc
module load cuda/11.1.1
module load openmpi/3.1.6-gcc8.3.1
PATH=$PATH:/jet/home/schwinns/pkgs/gromacs/2020.5
source /jet/home/schwinns/pkgs/gromacs/2020.5/bin/GMXRC

export GMX_MAXBACKUP=-1  # do not make back-ups
export GMX_MAXCONSTRWARN=-1

#NPT (extend to 300 ns)
gmx convert-tpr -s ion_partition.tpr -extend 200000 -o ion_partition2.tpr
gmx mdrun -cpi ion_partition.cpt -s ion_partition2.tpr -deffnm ion_partition -ntomp 1
